package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnSubjects = new javax.swing.JButton();
        btnCourseInstructor = new javax.swing.JButton();
        btnStudentGrade = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnMainClass = new javax.swing.JButton();
        btnSchedule = new javax.swing.JButton();
        btnFaculty_Course = new javax.swing.JButton();
        btnFamiliar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoSchool.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setText("Quản lý trường học");

        btnSubjects.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSubjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoCourses.png"))); // NOI18N
        btnSubjects.setText("Quản lý thông tin các khóa học");
        btnSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectsActionPerformed(evt);
            }
        });

        btnCourseInstructor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCourseInstructor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoTeach.png"))); // NOI18N
        btnCourseInstructor.setText("Quản lý thông tin phân công giảng dạy");
        btnCourseInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseInstructorActionPerformed(evt);
            }
        });

        btnStudentGrade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnStudentGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoResult.png"))); // NOI18N
        btnStudentGrade.setText("Quản lý kết quả khóa học");
        btnStudentGrade.setMaximumSize(new java.awt.Dimension(315, 79));
        btnStudentGrade.setMinimumSize(new java.awt.Dimension(315, 79));
        btnStudentGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentGradeActionPerformed(evt);
            }
        });

        btnUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoUser.png"))); // NOI18N
        btnUser.setText("Quản lý người dùng");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnMainClass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnMainClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoMainClass.png"))); // NOI18N
        btnMainClass.setText("Quản lý lớp");
        btnMainClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainClassActionPerformed(evt);
            }
        });

        btnSchedule.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoSchedule.png"))); // NOI18N
        btnSchedule.setText("Thời khóa biểu");
        btnSchedule.setMaximumSize(new java.awt.Dimension(315, 79));
        btnSchedule.setMinimumSize(new java.awt.Dimension(315, 79));
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });

        btnFaculty_Course.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFaculty_Course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoFaculty.png"))); // NOI18N
        btnFaculty_Course.setText("Quản lý khóa/khoa");
        btnFaculty_Course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaculty_CourseActionPerformed(evt);
            }
        });

        btnFamiliar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFamiliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoFamiliar.png"))); // NOI18N
        btnFamiliar.setText("Quản lý thân nhân");
        btnFamiliar.setMaximumSize(new java.awt.Dimension(315, 79));
        btnFamiliar.setMinimumSize(new java.awt.Dimension(315, 79));
        btnFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamiliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(477, 477, 477))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStudentGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnMainClass, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                        .addComponent(btnSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCourseInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFaculty_Course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFamiliar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubjects)
                    .addComponent(btnUser))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseInstructor))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainClass)
                    .addComponent(btnFaculty_Course))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectsActionPerformed
        Subjects courses = new Subjects();
        courses.setLocationRelativeTo(null);
        courses.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSubjectsActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        User user = new User();
        user.setLocationRelativeTo(null);
        user.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnMainClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainClassActionPerformed
        MainClass mainClass = new MainClass();
        mainClass.setLocationRelativeTo(null);
        mainClass.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMainClassActionPerformed

    private void btnFaculty_CourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaculty_CourseActionPerformed
        Faculty_Course facuCourse = new Faculty_Course();
        facuCourse.setLocationRelativeTo(null);
        facuCourse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFaculty_CourseActionPerformed

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
        Schedule schedule = new Schedule();
        schedule.setLocationRelativeTo(null);
        schedule.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnScheduleActionPerformed

    private void btnFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamiliarActionPerformed
        Familiar familiar = new Familiar();
        familiar.setLocationRelativeTo(null);
        familiar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFamiliarActionPerformed

    private void btnCourseInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseInstructorActionPerformed
        CourseInstructor courseInstructor = new CourseInstructor();
        courseInstructor.setLocationRelativeTo(null);
        courseInstructor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCourseInstructorActionPerformed

    private void btnStudentGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentGradeActionPerformed
        StudentGrade studentGrade = new StudentGrade();
        studentGrade.setLocationRelativeTo(null);
        studentGrade.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStudentGradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Index index = new Index();
                index.setLocationRelativeTo(null);
                index.setVisible(true);
                index.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseInstructor;
    private javax.swing.JButton btnFaculty_Course;
    private javax.swing.JButton btnFamiliar;
    private javax.swing.JButton btnMainClass;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JButton btnStudentGrade;
    private javax.swing.JButton btnSubjects;
    private javax.swing.JButton btnUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
