/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.*;
import BUS.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class MainClass extends javax.swing.JFrame {

    ArrayList<MainClassTable> mainClass;
    BUSMainClass bus = new BUSMainClass();
    /**
     * Creates new form MainClass
     */
    public MainClass() {
        initComponents();
        showClass("","");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMainClass = new javax.swing.JTable();
        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblClassName = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnIndex = new javax.swing.JToggleButton();
        lblClassType = new javax.swing.JLabel();
        lblClass_UserID = new javax.swing.JLabel();
        txtClass_UserID = new javax.swing.JTextField();
        btnView_UserID = new javax.swing.JButton();
        cbClassType = new javax.swing.JComboBox<>();
        lblClass_TeacherID = new javax.swing.JLabel();
        txtClass_TeacherID = new javax.swing.JTextField();
        btnView_TeacherID = new javax.swing.JButton();
        lblClass_FacultyID = new javax.swing.JLabel();
        txtClass_FacultyID = new javax.swing.JTextField();
        btnView_FacultyID = new javax.swing.JButton();
        lblClass_PeriodID = new javax.swing.JLabel();
        txtClass_PeriodID = new javax.swing.JTextField();
        btnView_PeriodID = new javax.swing.JButton();
        cbSearch = new javax.swing.JComboBox<>();
        btnSearch1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMainClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblMainClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMainClassMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMainClass);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoMainClass.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setText("Quản lý lớp");

        lblClassName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClassName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconClassName.png"))); // NOI18N
        lblClassName.setText("Tên lớp :");

        txtClassName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconSearch.png"))); // NOI18N
        btnSearch.setPreferredSize(new java.awt.Dimension(32, 32));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconAdd.png"))); // NOI18N
        btnAdd.setText("Thêm ");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconDelete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnIndex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnIndex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoSchool-40.png"))); // NOI18N
        btnIndex.setText("Về trang chủ");
        btnIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndexActionPerformed(evt);
            }
        });

        lblClassType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClassType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconType.png"))); // NOI18N
        lblClassType.setText("Loại lớp :");

        lblClass_UserID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClass_UserID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconUserID.png"))); // NOI18N
        lblClass_UserID.setText("Mã số sinh viên :");

        txtClass_UserID.setEditable(false);
        txtClass_UserID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtClass_UserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClass_UserIDActionPerformed(evt);
            }
        });

        btnView_UserID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconEye.png"))); // NOI18N
        btnView_UserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView_UserIDActionPerformed(evt);
            }
        });

        cbClassType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbClassType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Loại lớp --", "Chính quy", "Cao đẳng" }));
        cbClassType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClassTypeActionPerformed(evt);
            }
        });

        lblClass_TeacherID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClass_TeacherID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconTeacher.png"))); // NOI18N
        lblClass_TeacherID.setText("Cố vấn học tập :");

        txtClass_TeacherID.setEditable(false);
        txtClass_TeacherID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtClass_TeacherID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClass_TeacherIDActionPerformed(evt);
            }
        });

        btnView_TeacherID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconEye.png"))); // NOI18N
        btnView_TeacherID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView_TeacherIDActionPerformed(evt);
            }
        });

        lblClass_FacultyID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClass_FacultyID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconFacultyName.png"))); // NOI18N
        lblClass_FacultyID.setText("Khoa :");

        txtClass_FacultyID.setEditable(false);
        txtClass_FacultyID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtClass_FacultyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClass_FacultyIDActionPerformed(evt);
            }
        });

        btnView_FacultyID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconEye.png"))); // NOI18N
        btnView_FacultyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView_FacultyIDActionPerformed(evt);
            }
        });

        lblClass_PeriodID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClass_PeriodID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconPeriod.png"))); // NOI18N
        lblClass_PeriodID.setText("Niên khóa :");

        txtClass_PeriodID.setEditable(false);
        txtClass_PeriodID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtClass_PeriodID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClass_PeriodIDActionPerformed(evt);
            }
        });

        btnView_PeriodID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconEye.png"))); // NOI18N
        btnView_PeriodID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView_PeriodIDActionPerformed(evt);
            }
        });

        cbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MSSV", "Tên SV", "Tên lớp", "Giảng viên" }));

        btnSearch1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch1.setText("X");
        btnSearch1.setPreferredSize(new java.awt.Dimension(32, 32));
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(651, 651, 651))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(46, 46, 46)
                        .addComponent(btnDelete)
                        .addGap(35, 35, 35)
                        .addComponent(btnIndex)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblClass_PeriodID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                        .addComponent(txtClass_PeriodID, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblClass_TeacherID)
                                            .addComponent(lblClass_FacultyID))
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtClass_FacultyID, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                            .addComponent(txtClass_TeacherID))))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnView_TeacherID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnView_FacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(btnView_PeriodID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblClassName)
                                            .addComponent(lblClassType))
                                        .addGap(116, 116, 116)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbClassType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtClassName)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblClass_UserID)
                                        .addGap(55, 55, 55)
                                        .addComponent(txtClass_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addComponent(btnView_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClassName)
                            .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClassType)
                            .addComponent(cbClassType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClass_UserID)
                            .addComponent(txtClass_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView_UserID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClass_TeacherID)
                            .addComponent(txtClass_TeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView_TeacherID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClass_FacultyID)
                            .addComponent(txtClass_FacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView_FacultyID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClass_PeriodID)
                            .addComponent(txtClass_PeriodID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView_PeriodID)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnIndex))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1342, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String message = bus.addMainClass(txtClassName.getText(), cbClassType.getSelectedItem().toString(),
                txtClass_UserID.getText(), txtClass_TeacherID.getText(),
                txtClass_FacultyID.getText(), txtClass_PeriodID.getText());
        JOptionPane.showMessageDialog(rootPane, message);
        showClass("", "");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndexActionPerformed
        Index index = new Index();
        index.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIndexActionPerformed

    private void txtClass_UserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClass_UserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClass_UserIDActionPerformed

    private void cbClassTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClassTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbClassTypeActionPerformed

    private void txtClass_TeacherIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClass_TeacherIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClass_TeacherIDActionPerformed

    private void txtClass_FacultyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClass_FacultyIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClass_FacultyIDActionPerformed

    private void txtClass_PeriodIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClass_PeriodIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClass_PeriodIDActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int q = JOptionPane.showConfirmDialog(rootPane, "Lưu ý! Sinh viên sẽ bị xóa, bạn có muốn tiếp tục?");
        if (q == 0) {
            String message = bus.deleteMainClass(mainClass.get(tblMainClass.getSelectedRow()).getId()+"");
            JOptionPane.showMessageDialog(rootPane, message);
            showClass("", "");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnView_UserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView_UserIDActionPerformed
       XEMDACHSACH f = new XEMDACHSACH();
        f.showStudent(this.txtClass_UserID);
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnView_UserIDActionPerformed

    private void btnView_TeacherIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView_TeacherIDActionPerformed
        XEMDACHSACH f = new XEMDACHSACH();
        f.showTeacher(this.txtClass_TeacherID);
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnView_TeacherIDActionPerformed

    private void btnView_FacultyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView_FacultyIDActionPerformed
        XEMDACHSACH f = new XEMDACHSACH();
        f.showFal(this.txtClass_FacultyID);
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnView_FacultyIDActionPerformed

    private void btnView_PeriodIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView_PeriodIDActionPerformed
        XEMDACHSACH f = new XEMDACHSACH();
        f.showCourse(this.txtClass_PeriodID);
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnView_PeriodIDActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (txtSearch.getText().equals("Tìm kiếm ...")) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập gì cả!");
        } else {
            showClass(txtSearch.getText(), cbSearch.getSelectedItem().toString());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        if (txtSearch.getText().equals("Tìm kiếm ...")) {
            txtSearch.setText("");
            txtSearch.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        if (txtSearch.getText().equals("")) {
            txtSearch.setText("Tìm kiếm ...");
            txtSearch.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        showClass("", "");
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void tblMainClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainClassMouseClicked
//        int i = tblMainClass.getSelectedRow();
    }//GEN-LAST:event_tblMainClassMouseClicked

    private void showClass(String searchKey, String type) {
        DefaultTableModel model = new DefaultTableModel();
        Object[] columns = {"Tên lớp", "MSSV", "Tên sinh viên", "Khóa", "Khoa", "Hệ", "Giảng viên phụ trách",};
        model.setColumnIdentifiers(columns);

        mainClass = bus.showClass(searchKey, type);
        for (int i = 0; i < mainClass.size(); i++) {
            model.addRow(new Object[]{
                mainClass.get(i).getClassName(),
                mainClass.get(i).getUserID(),
                mainClass.get(i).getName(),
                mainClass.get(i).getCourseName(),
                mainClass.get(i).getFacultyName(),
                mainClass.get(i).getType(),
                mainClass.get(i).getTeacher(),
            });
        }
        tblMainClass.setModel(model);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                MainClass mainClass = new MainClass();
                mainClass.setLocationRelativeTo(null);
                mainClass.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JToggleButton btnIndex;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnView_FacultyID;
    private javax.swing.JButton btnView_PeriodID;
    private javax.swing.JButton btnView_TeacherID;
    private javax.swing.JButton btnView_UserID;
    private javax.swing.JComboBox<String> cbClassType;
    private javax.swing.JComboBox<String> cbSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClassName;
    private javax.swing.JLabel lblClassType;
    private javax.swing.JLabel lblClass_FacultyID;
    private javax.swing.JLabel lblClass_PeriodID;
    private javax.swing.JLabel lblClass_TeacherID;
    private javax.swing.JLabel lblClass_UserID;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMainClass;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtClass_FacultyID;
    private javax.swing.JTextField txtClass_PeriodID;
    private javax.swing.JTextField txtClass_TeacherID;
    private javax.swing.JTextField txtClass_UserID;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
