/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.*;
import DTO.*;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gnoob
 */
public class XEMDACHSACH extends javax.swing.JFrame {


    DefaultTableModel model;
    BUSFaculty_Course busFalCo = new BUSFaculty_Course();
    BUSSubjects busSub = new BUSSubjects();
    BUSUser busUser = new BUSUser();
    JTextField tField = new JTextField();
    private String searchKey="";
    private String cList=""; //Danh sách hiện tại
    
    
    public XEMDACHSACH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("CHỌN DS");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm theo mã");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Bạn đang chọn mã:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchKey = txtSearch.getText();
        if (cList.equals("faculty")) showFal(tField);
        else if (cList.equals("course")) showCourse(tField);
        else if (cList.equals("subject")) showSubject(tField);
        else if (cList.equals("student")) showStudent(tField);
        else if (cList.equals("teacher")) showStudent(tField);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int i = table.getSelectedRow();
        txt.setText(table.getModel().getValueAt(i, 0).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tField.setText(txt.getText());
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    public void showFal(JTextField txt){
        ArrayList <Faculty> fal = busFalCo.showFaculty(searchKey);
        cList="faculty";
        tField = txt;
        label.setText("Chọn một khoa!");
        btnSearch.setText("Tìm theo tên khoa");
        
        model = new DefaultTableModel();
        Object [] columns = {"Mã khoa","Tên Khoa"};
        model.setColumnIdentifiers(columns);
        
        for (int i=0; i< fal.size();i++){
            String name = fal.get(i).getName();
            boolean notFound = name.toUpperCase().indexOf(searchKey.toUpperCase()) == -1;
            if (searchKey!="" && notFound) continue;
            model.addRow(new Object[]{
                fal.get(i).getId(),
                name,
            });
        }
        table.setModel(model);
    }
    
    public void showCourse(JTextField txt){
        ArrayList <Course> cou = busFalCo.showCourse(searchKey);
        cList="course";
        tField = txt;
        label.setText("Chọn một khóa!");
        btnSearch.setText("Tìm theo tên khóa");
        
        model = new DefaultTableModel();
        Object [] columns = {"Mã khóa","Tên khóa"};
        model.setColumnIdentifiers(columns);
        
        for (int i=0; i< cou.size();i++){
            String name = cou.get(i).getName();
            boolean notFound = name.toUpperCase().indexOf(searchKey.toUpperCase()) == -1;
            if (searchKey!="" && notFound) continue;
            model.addRow(new Object[]{
                cou.get(i).getId(),
                name,
            });
        }
        table.setModel(model);
    }
    
    public void showSubject(JTextField txt){
        ArrayList <SubjectTable> sub = busSub.showSuject("", "");
        cList="subject";
        tField = txt;
        label.setText("Chọn một môn học!");
        btnSearch.setText("Tìm theo tên môn");
        
        model = new DefaultTableModel();
        Object [] columns = {"Mã môn","Tên môn học"};
        model.setColumnIdentifiers(columns);
        
        for (int i=0; i< sub.size();i++){
            String name = sub.get(i).getName();
            boolean notFound = name.toUpperCase().indexOf(searchKey.toUpperCase()) == -1;
            if (searchKey!="" && notFound) continue;
            model.addRow(new Object[]{
                sub.get(i).getId(),
                name,
            });
        }
        table.setModel(model);
    }
    
    public void showStudent(JTextField txt){
        ArrayList <UserTable> student = busUser.showUser("Sinh viên", "Chức vụ");
        cList="student";
        tField = txt;
        label.setText("Chọn một sinh viên!");
        btnSearch.setText("Tìm theo tên");
        
        model = new DefaultTableModel();
        Object [] columns = {"Mã số","Tên sinh viên"};
        model.setColumnIdentifiers(columns);
        
        for (int i=0; i< student.size();i++){
            String name = student.get(i).getName();
            boolean notFound = name.toUpperCase().indexOf(searchKey.toUpperCase()) == -1;
            if (searchKey!="" && notFound) continue;
            model.addRow(new Object[]{
                student.get(i).getId(),
                name,
            });
        }
        table.setModel(model);
    }
    
    public void showTeacher(JTextField txt){
        ArrayList <UserTable> teacher = busUser.showUser("Giảng viên", "Chức vụ");
        cList="teacher";
        tField = txt;
        label.setText("Chọn một giảng viên!");
        btnSearch.setText("Tìm theo tên");
        
        model = new DefaultTableModel();
        Object [] columns = {"Mã số","Tên tài khoản"};
        model.setColumnIdentifiers(columns);
        
        for (int i=0; i< teacher.size();i++){
            String name = teacher.get(i).getName();
            boolean notFound = name.toUpperCase().indexOf(searchKey.toUpperCase()) == -1;
            if (searchKey!="" && notFound) continue;
            model.addRow(new Object[]{
                teacher.get(i).getId(),
                name,
            });
        }
        table.setModel(model);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XEMDACHSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XEMDACHSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XEMDACHSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XEMDACHSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XEMDACHSACH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
